home/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from .import views

app_name='home'

urlpatterns = [
    path('',views.HomeView,name='home'),
    path('add/cust/',views.AddCustomerView,name='add_customer'),
    path('handel/',views.HandelView,name='handel'),
    path('handel/<int:id>',views.HandelDetailsView,name='handel_details'),
    path('assign/<int:id>',views.AssignView,name='assign'),
    path('myassign/',views.MyAssignView,name='my_assign'),
    path('edit/cust/<int:id>',views.EditCustView,name='edit_cust'),
    path('remove/assign/<int:id>',views.RemoveAssignView,name='remove_aasign'),
    path('login/',views.LoginView,name='login'),
    path('logout/',views.LogoutView,name="logout"), 
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home_page')),
]

home/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

import os
# Create your models here.
Gender = (
    ('Male','ذكر'),
    ('Female','أنثي'), 
)
Help = (
    ('Money','مال'),
    ('Food','طعام'),
    ('Medicine','دواء'),
)
Partner = (
    ('Yes','نعم'),
    ('No','لا'),
    ('Single','غير متزوج'),
)
Cust_Status = (
    ('hold','بالإنتظار'),
    ('verify','تأكيد البيانات'),
    ('handling','تتم المساعده'),
    ('done','تمت المساعده'),
)
def customer_img(instance, filename):
    ext = filename.split('.')[-1]
    filename = "BDP_%s.%s" % (instance.id, ext)
    return os.path.join('BDP', filename)
class Customer(models.Model):
    ssn = models.CharField(max_length=14)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=300)
    gender = models.CharField(max_length=6,choices=Gender)
    help_type = MultiSelectField(choices=Help)
    partner_alive = models.CharField(max_length=6,choices=Partner)
    number_children = models.IntegerField(default=0,validators=[MaxValueValidator(50),MinValueValidator(0)])
    number_brother = models.IntegerField(default=0)
    support = models.FloatField(default=0)
    comment = models.CharField(max_length=500,null=True,blank=True)
    status = models.CharField(max_length=9,choices=Cust_Status,default='hold')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name_plural = "Customer"
    def __str__(self):
        return self.name

class CustomerAttachments(models.Model):
    customer_key = models.ForeignKey(Customer,on_delete=models.CASCADE)
    attachments = models.ImageField(upload_to=customer_img)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name_plural = "CustomerAttachments"
    def __str__(self):
        return str(self.customer_key)
class CustomerHandel(models.Model):
    customer_key = models.OneToOneField(Customer,on_delete=models.CASCADE,unique=True)
    handel_by = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name_plural = "CustomerHandel"
    def __str__(self):
        return str(self.customer_key)+' '+str(self.handel_by)

home/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class CustomerForm(ModelForm):
    comment= forms.CharField(widget=forms.Textarea(attrs={"rows":10, "cols":30}),label='تفاصيل أكثر')
    class Meta:
        model = Customer
        fields = ['name','ssn','address','gender','help_type','partner_alive','number_children','number_brother','comment','support','status']
        labels = {
        "name": "الاسم بالكامل",
        "ssn": "الرقم القومي",
        "address": "العنوان",
        "gender": "النوع",
        "help_type": "نقدر نساعدك ازاي",
        "partner_alive": "هل الزوج/الزوجه علي قيد الحياة",
        "number_children": "عدد الأولاد",
        "number_brother": "عدد الاخوه",
        "support": "قيمة الدعم المقدم",
        "status": "حالة الطلب",

        }
        widgets = {
            'ssn': forms.TextInput(attrs={'required': True,'type':'number','placeholder':'الارقام بالإنجليزية'}),
        }

class CustomerAttachmentsForm(ModelForm):
    class Meta:
        model = CustomerAttachments
        fields = '__all__'
        labels = {
        "attachments": "المرفقات",
        }
        widgets = {
        'attachments': forms.ClearableFileInput(attrs={'multiple': True}),
        'customer_key': forms.TextInput(attrs={'required': False,'readonly':True, 'hidden':True}),
        }

home/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import auth
from .forms import *
from .models import *
from .filters import *
from .decorators import *
# Create your views here.
def HomeView(request):
    return render(request,'home.html')

def AddCustomerView(request):
    get_customer_form = CustomerForm()
    get_customer_attachments_form = CustomerAttachmentsForm()
    if request.method == 'POST':
        customer_form = CustomerForm(request.POST)
        attach_form = CustomerAttachmentsForm(request.POST,request.FILES)
        if customer_form.is_valid():
            customer_form.name = request.POST['name']
            customer_form.address = request.POST['address']
            customer_form.gender = request.POST['gender']
            customer_form.help_type = request.POST['help_type']
            customer_form.partner_alive = request.POST['partner_alive']
            customer_form.number_children = request.POST['number_children']
            customer_form.number_brother = request.POST['number_brother']
            customer_form.ssn = request.POST['ssn']
            customer_form.comment = request.POST['comment']
            customer_form.support = request.POST['support']
            customer_form.status = request.POST['status']

            ssn_len = len(customer_form.ssn)
            attachments = request.FILES.getlist('attachments')
            if int(ssn_len) == int(14):
                x = customer_form.save()
                if x:
                    for attach in attachments:
                        insert_attach = CustomerAttachments.objects.create(
                            customer_key = Customer.objects.latest('id'),
                            attachments = attach,
                        )
                messages.info(request,"تم إستلام الطلب")
                return redirect(reverse("home_page:home"))
            else:
                messages.info(request,"خطأ بالبيانات")
        else:
            messages.info(request,"خطأ بالبيانات")
    context = {'form':get_customer_form,'attach':get_customer_attachments_form}
    return render(request,'add_customer.html',context)

@unauthenticated_user
def HandelView(request):
    get_cust_data = Customer.objects.all()
    ##Filter
    my_filter = CustFilter(request.GET,queryset=get_cust_data)
    get_cust_data = my_filter.qs
    get_cust_handel = CustomerHandel.objects.filter(customer_key__in=get_cust_data)
    context = {'form':get_cust_data,'handel':get_cust_handel,'filter':my_filter}
    return render(request,'handel.html',context)

@unauthenticated_user
def HandelDetailsView(request,id):
    get_cust_data = Customer.objects.get(id=id)
    try:
        get_cust_attach = CustomerAttachments.objects.filter(customer_key=get_cust_data)
    except:
        get_cust_attach = ''
    try:
        get_cust_handel = CustomerHandel.objects.get(customer_key=get_cust_data)
    except:
        get_cust_handel = ''
    context = {'form':get_cust_data,'handel':get_cust_handel,'attach':get_cust_attach}
    return render(request,'handel_details.html',context)

@unauthenticated_user
def AssignView(request,id):
    get_cust_data = Customer.objects.get(id=id)
    if request.method == 'POST':
        get_cust_id = request.POST['cust_id']
        get_cust = Customer.objects.get(id=get_cust_id)
        Customer.objects.filter(id=id).update(status='verify')
        CustomerHandel.objects.create(handel_by=request.user,customer_key=get_cust)
        messages.info(request,"تم تبني الحالة")
        return redirect(reverse("home_page:my_assign"))
    context = {'form':get_cust_data}
    return render(request,'assign.html',context)

@unauthenticated_user
def MyAssignView(request):
    get_cust_handel_data = CustomerHandel.objects.filter(handel_by=request.user)
    context = {'form':get_cust_handel_data}
    return render(request,'my_assign.html',context)

@unauthenticated_user
def EditCustView(request,id):
    get_cust_data = get_object_or_404(Customer,id=id)
    if request.method == 'POST':
        form = CustomerForm(request.POST,instance=get_cust_data)
        form.save()
        messages.info(request,"تم التعديل")
        return redirect(reverse("home_page:my_assign"))
    else:
        form = CustomerForm(instance=get_cust_data)
    context = {'form':form}
    return render(request,'edit_cust.html',context)

@unauthenticated_user
def RemoveAssignView(request,id):
    get_assign = CustomerHandel.objects.get(handel_by=request.user,id=id)
    get_cust = get_assign.customer_key
    if request.method == 'POST':
        get_assign.delete()
        get_cust.status = 'hold'
        get_cust.save()
        messages.info(request,"تم حذف التبني")
        return redirect(reverse("home_page:my_assign"))
    return render(request,'remove_assign.html')

def LoginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/handel')
            else:
                messages.info(request, 'الحساب غير مفعل من قبل إدارة الموقع')                
        else:
            messages.info(request, 'بيانات خاطئة! من فضلك اعد المحاولة')
    context = {}
    return render(request, 'login.html',context)

@unauthenticated_user
def LogoutView(request):
    auth.logout(request)
    return redirect('/')

home/templates/add_customer.html
<!DOCTYPE html>
{% extends "frontend/front_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
  {% block main %}
    <div class="container position-relative">
      <div class="row align-items-center">
        <div class="col-md-12 order-md-1 pt-8">
          <div class="card">
            <div class="card-header">
              بيانات مطلوبة علشان نقدر نساعدك
            </div>
            <div class="card-body">
              <h5 class="card-title">
                {% for message in messages %}
                <div class="dj_msg alert alert-danger alert-dismissible fade show" role="alert">
                  {{message}}
                </div>
                {% endfor %}
              </h5>
              <p class="card-text">
                <form class="row g-3 needs-validation" enctype="multipart/form-data" method="post" autocomplete="off" novalidate>
                  {% csrf_token %}
                  <div class="col-6">
                    {{form.name | as_crispy_field}}
                  </div>
                  <div class="col-6">
                    {{form.ssn | as_crispy_field}}
                  </div>
                  <div class="col-12">
                    {{form.address | as_crispy_field}}
                  </div>
                  <div class="col-md-4">
                    {{form.gender | as_crispy_field}}
                  </div>
                  <div class="col-md-4">
                    {{form.partner_alive | as_crispy_field}}
                  </div>
                  <div class="col-md-4">
                    {{form.number_children | as_crispy_field}}
                  </div>
                  <div class="col-md-4">
                    {{form.number_brother | as_crispy_field}}
                  </div>
                  <div class="col-md-4">
                    {{form.help_type | as_crispy_field}}
                  </div>                  
                  <div class="row">
                    <div class="col-md-4">
                      {{attach.attachments | as_crispy_field}}
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item disabled" aria-disabled="true">شهادة ميلادك او بطاقة الرقم القومي</li>
                        <li class="list-group-item disabled" aria-disabled="true">شهادة ميلاد او وفاة الزوج او الزوجه ان وجد</li>
                        <li class="list-group-item disabled" aria-disabled="true">شهادة ميلاد الاولاد ان وجد</li>
                        <li class="list-group-item disabled" aria-disabled="true">شهادة ميلاد الاخوات ان وجد</li>
                        <li class="list-group-item disabled" aria-disabled="true">التحاليل او الاشعه او التقارير الطبيه في حالة الحاجه الي ادوية</li>
                      </ul>
                    </div>
                    <div class="col-md-8">
                      {{form.comment | as_crispy_field}}
                    </div>
                  </div>
                  <input type="hidden" name="support" value="0">
                  <input type="hidden" name="status" value="hold">
                  <div class="col-12">
                    <button type="submit" class="btn btn-primary">إرسال الطلب</button>
                  </div>
                </form>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script type="text/javascript">
  // Example starter JavaScript for disabling form submissions if there are invalid fields
(function () {
  'use strict'
  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  var forms = document.querySelectorAll('.needs-validation')
  // Loop over them and prevent submission
  Array.prototype.slice.call(forms)
    .forEach(function (form) {
      form.addEventListener('submit', function (event) {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }
        form.classList.add('was-validated')
      }, false)
    })
})()
  </script>
  {% endblock %}

home/templates/assign.html
<!DOCTYPE html>
{% extends "frontend/front_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
  {% block main %}
    <div class="container position-relative">
      <div class="row align-items-center">
        <div class="col-md-12 order-md-1 pt-8">
          <div class="card">
            <div class="card-header">
              تبني الحالة
            </div>
            <div class="card-body">
              <h5 class="card-title">
                {% for message in messages %}
                <div class="dj_msg alert alert-danger alert-dismissible fade show" role="alert">
                  {{message}}
                </div>
                {% endfor %}
              </h5>
              <p class="card-text">
                <form class="row g-3" enctype="multipart/form-data" method="post" autocomplete="off">
                  {% csrf_token %}
                  <input type="hidden" name="cust_id" value="{{form.id}}">
                  <div class="card text-white bg-secondary mb-6">
                    <div class="card-header">تبني الحالة</div>
                    <div class="card-body">
                      <p class="card-text">
                        عند الضفط علي موافق عليك التواصل مع الحالة للتأكد من البيانات وتقديم الدعم الطلوب ولن يستطيع اي من الفريق العمل علي هذه الحالة غيرك
                      </p>
                      <button type="submit" class="btn btn-success">موافق</button>
                    </div>
                  </div>
                </form>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endblock %}

home/templates/handel.html
<!DOCTYPE html>
{% extends "frontend/front_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
  {% block main %}
    <div class="container position-relative">
      <div class="row align-items-center">
        <div class="col-md-12 order-md-1 pt-8">
          <div class="card">
            <div class="card-header">
            حالات بحاجة الي مساعده              
            </div>
            <div class="card-body">
              <h5 class="card-title">
                {% for message in messages %}
                <div class="dj_msg alert alert-danger alert-dismissible fade show" role="alert">
                  {{message}}
                </div>
                {% endfor %}
              </h5>
              <p class="card-text">
                  <div class="table-responsive">
                    <div class="row">
                      <div class="col-10">
                        <table class="table table-bordered border-primary display" id="cust_data">
                          <thead>
                            <tr>
                              <th scope="col">#</th>
                              <th scope="col">الرقم القومي</th>
                              <th scope="col">الاسم</th>
                              <th scope="col">نوع المساعدة</th>
                              <th scope="col">الحالة</th>
                              <th scope="col">يعمل علي الحاله</th>
                              <th scope="col">تفاصيل</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for data in form %}
                            <tr>
                              <th scope="row">{{data.id}}</th>
                              <td>{{data.ssn}}</td>
                              <td>{{data.name}}</td>
                              <td>{{data.help_type}}</td>
                              <td>
                                {% if data.status == 'hold' %}
                                بالإنتظار
                                {% elif data.status == 'verify' %}
                                تأكيد البيانات
                                {% elif data.status == 'handling' %}
                                تتم المساعده
                                {% elif data.status == 'done' %}
                                تمت المساعده
                                {% endif %}
                              </td>
                              <td>
                                {% for handel in handel %}
                                  {% if data.id == handel.customer_key.id %}
                                    {{ handel.handel_by.first_name}} {{ handel.handel_by.last_name}}
                                  {% endif %}
                                {% endfor %}
                              </td>
                              <td scope="col"><a href="{% url 'home_page:handel_details' data.id %}"><button type="button" class="btn btn-warning"><i class="fas fa-angle-double-left"></i></button></a></td>
                            </tr>
                            {% endfor %}
                          </tbody>
                          <tfoot>
                            <tr>
                              <th scope="col">#</th>
                              <th scope="col">الرقم القومي</th>
                              <th scope="col">الاسم</th>
                              <th scope="col">نوع المساعدة</th>
                              <th scope="col">الحالة</th>
                              <th scope="col">يعمل علي الحاله</th>
                              <th scope="col">تفاصيل</th>
                            </tr>
                          </tfoot>
                      </table>
                    </div>
                    <div class="col-2">
                      <form class="form" method="get">
                        {% bootstrap_form filter.form %}
                        <button type="submit" class="btn btn-success">موافق</button>
                      </form>
                    </div>
                  </div>
                </div>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" type="text/javascript"></script>
<script>
    $(document).ready( function () {
      $('#cust_data').DataTable();
  } );
</script>
  {% endblock %}

home/templates/handel_details.html
<!DOCTYPE html>
{% extends "frontend/front_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
  {% block main %}
    <div class="container position-relative">
      <div class="row align-items-center">
        <div class="col-md-12 order-md-1 pt-8">
          <div class="card">
            <div class="card-header">
              {{form.name}}
            </div>
            <div class="card-body">
              <h5 class="card-title">
                {% for message in messages %}
                <div class="dj_msg alert alert-danger alert-dismissible fade show" role="alert">
                  {{message}}
                </div>
                {% endfor %}
              </h5>
              <p class="card-text">
                <table class="table table-bordered border-primary display">
                  <thead>
                    <tr>
                      <th scope="col" class="table-light">تقديم الدعم</th>
                      <th scope="col">
                        {% if handel.handel_by %}
                        {{handel.handel_by.first_name}} لقد تبني هذه الحالة
                        {% else %}
                        <a href="{% url 'home_page:assign' form.id %}">
                        <button type="button" class="btn btn-outline-warning">متاح</button>
                        </a>
                        {% endif %}
                      </th>
                    </tr>
                  </thead>
                </table>
                <table class="table table-bordered border-primary display">
                  <thead>
                    <tr>
                      <th scope="col" class="table-success">قمية الدعم المقدم</th>
                      <th scope="col">{{form.support | floatformat:2}}</th>
                      <th scope="col" class="table-success">حالة الطلب</th>
                      <th scope="col">
                        {% if form.status == 'hold' %}
                        بالإنتظار
                        {% elif form.status == 'verify' %}
                        تأكيد البيانات
                        {% elif form.status == 'handling' %}
                        تتم المساعده
                        {% elif form.status == 'done' %}
                        تمت المساعده
                        {% endif %}
                      </th>
                    </tr>
                  </thead>
                </table>
                <table class="table table-bordered border-primary display">
                  <thead>
                    <tr>
                      <th scope="col" class="table-warning">الرقم القومي</th>
                      <th scope="col">{{form.ssn}}</th>
                      <th scope="col" class="table-warning">الاسم</th>
                      <th scope="col">{{form.name}}</th>
                    </tr>
                    <tr>
                      <th scope="col" class="table-warning">العنوان</th>
                      <th scope="col">{{form.address}}</th>
                      <th scope="col" class="table-warning">النوع</th>
                      <th scope="col">
                        {% if form.gender == 'Male' %}
                        ذكر
                        {% elif form.gender == 'Female'%}
                        أنثي
                        {% endif %}
                      </th>
                    </tr>
                    <tr>
                      <th scope="col" class="table-warning">المساعدة المطلوبة</th>
                      <th scope="col">{{form.help_type}}</th>
                      <th scope="col" class="table-warning">هل الشريك علي قيد الحياة</th>
                      <th scope="col">
                        {% if form.partner_alive == 'Yes' %}
                        نعم
                        {% elif form.partner_alive == 'No' %}
                        لا
                        {% elif form.partner_alive == 'Single' %}
                        غير متزوج
                        {% endif %}
                      </th>
                    </tr>
                    <tr>
                      <th scope="col" class="table-warning">عدد الأطفال</th>
                      <th scope="col">{{form.number_children}}</th>
                      <th scope="col" class="table-warning">عدد الإخوة</th>
                      <th scope="col">{{form.number_brother}}</th>
                    </tr>
                    <tr>
                      <th scope="col" class="table-warning">تفاصيل اكثر</th>
                      <th scope="col" colspan="3">{{form.comment}}</th>
                    </tr>
                  </thead>
                </table>
                <table class="table table-bordered border-primary display">
                  <thead>
                    <tr>
                      {% for attach in attach%}
                      <th scope="col" class="table-light">
                        <a href="{{attach.attachments.url}}" target="_blank">
                          <img src="{{attach.attachments.url}}" class="rounded" alt="" style="width:200px;height:400px;">
                        </a>
                      </th>
                      {% endfor %}
                    </tr>
                  </thead>
                </table>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endblock %}

home/templates/home.html
<!DOCTYPE html>
{% extends "frontend/front_base.html" %}
{% load static %}
{% block main %}

    <div class="container position-relative">
      <div class="row align-items-center">
        <div class="col-md-5 col-lg-6 order-md-1 pt-8"><img class="img-fluid" src="{% static 'frontend/img/illustrations/hero-header.png' %}" alt="" /></div>
        <div class="col-md-7 col-lg-6 text-center text-md-start pt-5 pt-md-9">
          {% for message in messages %}
          <div class="dj_msg alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
          </div>
          {% endfor %}
          <h1 class="mb-4 display-3 fw-bold">وَمَنْ أَحْيَاهَا فَكَأَنَّمَا أَحْيَا النَّاسَ جَمِيعًا </h1>
            <a class="btn btn-lg btn-primary rounded-pill hover-top" href="{% url 'home_page:add_customer' %}" role="button">إطلب السند</a>
        </div>
      </div>
    </div>

  {% endblock %}

home/templates/logged_out.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
{% block content %}
  <p>Logged out!</p>  
  <a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

home/templates/my_assign.html
<!DOCTYPE html>
{% extends "frontend/front_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
  {% block main %}
    <div class="container position-relative">
      <div class="row align-items-center">
        <div class="col-md-12 order-md-1 pt-8">
          <div class="card">
            <div class="card-header">
              الحالات التي تساعدها
            </div>
            <div class="card-body">
              <h5 class="card-title">
                {% for message in messages %}
                <div class="dj_msg alert alert-danger alert-dismissible fade show" role="alert">
                  {{message}}
                </div>
                {% endfor %}
              </h5>
              <p class="card-text">
                <div class="table-responsive">
                  <table class="table table-bordered border-primary display" id="cust_data">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">الرقم القومي</th>
                        <th scope="col">الاسم</th>
                        <th scope="col">نوع المساعدة</th>
                        <th scope="col">قيمة الدعم المقدم</th>
                        <th scope="col">الحالة</th>
                        <th scope="col">تفاصيل/تعديل</th>
                        <th scope="col">حذف التبني</th>                        
                      </tr>
                    </thead>
                    <tbody>
                      {% for data in form %}
                      <tr>
                        <th scope="row">{{data.customer_key.id}}</th>
                        <td>{{data.customer_key.ssn}}</td>
                        <td>{{data.customer_key.name}}</td>
                        <td>{{data.customer_key.help_type}}</td>
                        <td>{{data.customer_key.support}} جنية</td>
                        <td>
                          {% if data.customer_key.status == 'hold' %}
                          بالإنتظار
                          {% elif data.customer_key.status == 'verify' %}
                          تأكيد البيانات
                          {% elif data.customer_key.status == 'handling' %}
                          تتم المساعده
                          {% elif data.customer_key.status == 'done' %}
                          تمت المساعده
                          {% endif %}
                        </td>
                        <td scope="col"><a href="{% url 'home_page:edit_cust' data.customer_key.id %}"><button type="button" class="btn btn-warning"><i class="fas fa-angle-double-left"></i></button></a></td>
                        <td scope="col"><a href="{% url 'home_page:remove_aasign' data.id %}"><button type="button" class="btn btn-danger"><i class="fas fa-trash"></i></button></a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                    <tfoot>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">الرقم القومي</th>
                        <th scope="col">الاسم</th>
                        <th scope="col">نوع المساعدة</th>
                        <th scope="col">قيمة الدعم المقدم</th>
                        <th scope="col">الحالة</th>
                        <th scope="col">تفاصيل/تعديل</th>
                        <th scope="col">حذف التبني</th>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" type="text/javascript"></script>
<script>
    $(document).ready( function () {
      $('#cust_data').DataTable();
  } );
</script>
  {% endblock %}