home/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from .import views

app_name='home'

urlpatterns = [
    path('',views.HomeView,name='home'),
    path('add/cust/',views.AddCustomerView,name='add_customer'),
    path('handel/',views.HandelView,name='handel'),
    path('handel/<int:id>',views.HandelDetailsView,name='handel_details'),
    path('assign/<int:id>',views.AssignView,name='assign'),
    path('myassign/',views.MyAssignView,name='my_assign'),
    path('edit/cust/<int:id>',views.EditCustView,name='edit_cust'),
    path('remove/assign/<int:id>',views.RemoveAssignView,name='remove_aasign'),
    path('login/',views.LoginView,name='login'),
    path('logout/',views.LogoutView,name="logout"), 
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home_page')),
]

templates/frontend/front_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ar-EG" dir="rtl">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>SUNAD</title>


    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'frontend/img/favicons/favicon-32x32.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'frontend/img/favicons/favicon-32x32.ico' %}">
    <link rel="manifest" href="{% static 'frontend/img/favicons/manifest.json' %}">
    <meta name="msapplication-TileImage" content="{% static 'frontend/img/favicons/mstile-150x150.png' %}">
    <meta name="theme-color" content="#ffffff">


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'frontend/css/jquery.dataTables.min.css' %}" />
    <link href="{% static 'frontend/css/theme.css' %}" rel="stylesheet" />
    <link href="{% static 'frontend/css/mystyle.css' %}" rel="stylesheet" />

  </head>


  <body>

    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->
    <main class="main" id="top">
      <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" data-navbar-on-scroll="data-navbar-on-scroll">
        <div class="container">
          <a class="navbar-brand d-flex align-items-center fw-bold fs-2" href="{% url 'home_page:home' %}">
            <!--<img class="d-inline-block me-3" src="{% static 'frontend/img/icons/logo.png' %}" alt="" />-->
            سند
          </a>
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto pt-2 pt-lg-0">
              <!--<li class="nav-item"><a class="nav-link fw-bold active" aria-current="page" href="#">دخول</a></li>-->
              {% if request.user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'home_page:handel' %}">ساعد</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'home_page:my_assign' %}">مساعداتي</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'home_page:logout' %}">خروج</a></li>
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'home_page:login' %}">دخول</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      
        <!--/.bg-holder-->
        {% block main %}
        {% endblock main %}

      <!-- <section> begin ============================-->
      <section class="py-2">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <div class="text-center">
                <p class="mb-0">&copy; All copyrights reserved to 
                  <a class="text-black" href="http://Sunad.org/" target="_blank">Sunad </a>
                </p>
              </div>
            </div>
          </div>
        </div><!-- end of .container-->
      </section>
      <!-- <section> close ============================-->
      <!-- ============================================-->


    </main>
    <!-- ===============================================-->
    <!--    End of Main Content-->
    <!-- ===============================================-->

    


    <!-- ===============================================-->
    <!--    JavaScripts-->
    <!-- ===============================================-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" type="text/javascript"></script>
    <script src="https://kit.fontawesome.com/b7479a2fa4.js" crossorigin="anonymous"></script>
    <script src="{% static 'frontend/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'frontend/js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'frontend/js/popper.min.js' %}"></script>
    <script src="{% static 'frontend/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'frontend/js/is.min.js' %}"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
    <script src="{% static 'frontend/js/theme.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'frontend/js/jquery.dataTables.min.js' %}"></script>
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500&amp;display=swap" rel="stylesheet">
  </body>

</html>